// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// UserCollectionDao is the data access object for table user_collection.
type UserCollectionDao struct {
	Table   string                // Table is the underlying table name of the DAO.
	Group   string                // Group is the database configuration group name of current DAO.
	Columns UserCollectionColumns // Columns contains all the column names of Table for convenient usage.
}

// UserCollectionColumns defines and stores column names for table user_collection.
type UserCollectionColumns struct {
	UserId       string //
	CollectionId string //
}

//  userCollectionColumns holds the columns for table user_collection.
var userCollectionColumns = UserCollectionColumns{
	UserId:       "user_id",
	CollectionId: "collection_id",
}

// NewUserCollectionDao creates and returns a new DAO object for table data access.
func NewUserCollectionDao() *UserCollectionDao {
	return &UserCollectionDao{
		Group:   "default",
		Table:   "user_collection",
		Columns: userCollectionColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *UserCollectionDao) DB() gdb.DB {
	return g.DB(dao.Group)
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *UserCollectionDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.Table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *UserCollectionDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
