// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/hades300/bill-center/cmd/bill-server/app/dao/internal"
)

// userCollectionDao is the data access object for table user_collection.
// You can define custom methods on it to extend its functionality as you wish.
type userCollectionDao struct {
	*internal.UserCollectionDao
}

var (
	// UserCollection is globally public accessible object for table user_collection operations.
	UserCollection = userCollectionDao{
		internal.NewUserCollectionDao(),
	}
)

// Fill with you ideas below.
